CREATE TABLE IF NOT EXISTS estoque
(
    codigo BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,  -- Campo de ID com auto-incremento
    descricao VARCHAR(255),                                   -- Descrição do item
    quantidade BIGINT,                                        -- Quantidade (assumido como tipo inteiro)
    status VARCHAR(50),                                        -- Status (assumido como um texto curto)
    local VARCHAR(255),                                        -- Local (assumido como texto)
    projeto_id BIGINT  -- Relacionamento com a tabela projeto
    );