CREATE TABLE IF NOT EXISTS public.item
(
    codigo BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default",
    quantidade BIGINT,
    status character varying(255) COLLATE pg_catalog."default",
    local character varying(255) COLLATE pg_catalog."default",
    projeto_id BIGINT,
    CONSTRAINT fk_projeto FOREIGN KEY (projeto_id) REFERENCES public.projeto(id)
    );